### ISSUE TITLE
About your this code 

### ISSUE THREAD

**Issue by xuanyuan33521** [Pompe-org/Pompe-HS#1]
Firstly ,very happy read your artical"Byzantine Ordered Consensus without 
Byzantine Oligarchy".
But，I have a question is that the code is Pomoe-hk.not your artical designed "Pompē: order-linearizable SMR"??
Because ,I am not found some code in your respository.

**Comment by yhzhang0128** [comment]
Hi, sorry for the late reply! I was busy with another paper submission and then the final..... I have just been back to this repo and I will work on it now. I will have the repo ready in January.

For your question, I guess you will need `git clone --recursive` instead of simply `git clone` so that the submodule can be downloaded as well.

**Comment by yhzhang0128** [comment]
The code is under the `pompe` branch of this repo: https://github.com/Pompe-org/libhotstuff

**Comment by xuanyuan33521** [comment]
非常高兴您能给我回复，也非常荣幸拜读您的文章。
再次谢谢您的指点。
I am very glad that you can reply to me, and I am honored to read your article.
Thank you again for your advice.
